<?php

namespace EntityBundle\Repository;

/**
 * amiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class amiRepository extends \Doctrine\ORM\EntityRepository
{
}
