<?php

namespace EntityBundle\Repository;

/**
 * AttachTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttachTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
