<?php

namespace EntityBundle\Repository;

/**
 * typeNotifRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class typeNotifRepository extends \Doctrine\ORM\EntityRepository
{
}
